version: '3.7'
services:
  db:
    image: mongo
    restart: always
    platform: linux/x86_64
    networks:
      - default
    ports:
      - "27017:27017"
    container_name: mongodb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db